-- MySQL Script generated by MySQL Workbench
-- Thu Dec  1 02:12:32 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema workshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema workshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workshop` DEFAULT CHARACTER SET utf8 ;
USE `workshop` ;

-- -----------------------------------------------------
-- Table `workshop`.`ws_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop`.`ws_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(125) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workshop`.`ws_party`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop`.`ws_party` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(16) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `players_limit` INT NOT NULL,
  `state` INT NOT NULL,
  `time` INT NULL,
  `created` DATETIME NOT NULL,
  `ended` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ws_party_ws_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_ws_party_ws_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `workshop`.`ws_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workshop`.`ws_party_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop`.`ws_party_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `party_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `connected` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`, `party_id`),
  INDEX `fk_ws_party_users_ws_party1_idx` (`party_id` ASC),
  INDEX `fk_ws_party_users_ws_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_ws_party_users_ws_party1`
    FOREIGN KEY (`party_id`)
    REFERENCES `workshop`.`ws_party` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ws_party_users_ws_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `workshop`.`ws_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workshop`.`ws_mission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop`.`ws_mission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(125) NOT NULL,
  `desc` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workshop`.`ws_party_missions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop`.`ws_party_missions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `party_id` INT NOT NULL,
  `mission_id` INT NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `created` DATETIME NOT NULL,
  `ended` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ws_party_missions_ws_party1_idx` (`party_id` ASC),
  INDEX `fk_ws_party_missions_ws_mission1_idx` (`mission_id` ASC),
  CONSTRAINT `fk_ws_party_missions_ws_party1`
    FOREIGN KEY (`party_id`)
    REFERENCES `workshop`.`ws_party` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ws_party_missions_ws_mission1`
    FOREIGN KEY (`mission_id`)
    REFERENCES `workshop`.`ws_mission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workshop`.`ws_party_beacons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workshop`.`ws_party_beacons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `party_id` INT NOT NULL,
  `major` VARCHAR(32) NOT NULL,
  `minor` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ws_party_beacons_ws_party1_idx` (`party_id` ASC),
  CONSTRAINT `fk_ws_party_beacons_ws_party1`
    FOREIGN KEY (`party_id`)
    REFERENCES `workshop`.`ws_party` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
